#!/bin/bash

mkdir ../logs 

echo "Running report ingester: ingest to fedora"

python /big2/dc/Digital-Collections/archival-objects/mcmaster-ontario-conservation-reports/report_ingest.py ./ &> ../logs/report_ingest_report.txt

echo "Done."
